version: "3"

x-python-image: &default_python_image python:3.11-slim
x-networks: &default_networks
  - hello-layers_ace-framework-network

x-build: &default_build
  context: .
  dockerfile: Dockerfile
  args:
    BASE_IMAGE: *default_python_image

x-secrets-environment: &secrets_environment
  OPENAI_API_KEY: ${OPENAI_API_KEY}

x-rabbitmq-username: &rabbitmq-username rabbit
x-rabbitmq-password: &rabbitmq-password carrot
x-rabbitmq-environment: &rabbitmq_environment
  AMQP_HOST_NAME: rabbitmq
  AMQP_USERNAME: *rabbitmq-username
  AMQP_PASSWORD: *rabbitmq-password

x-logging-environment: &logging_environment
  ACE_LOG_LEVEL: ${ACE_LOG_LEVEL:-}
  ACE_THIRD_PARTY_LOG_LEVEL: ${ACE_THIRD_PARTY_LOG_LEVEL:-}

x-command: &default_command ["python3", "main.py"]

x-healthcheck: &healthcheck
  test: ["CMD", "/usr/local/bin/check_resource_health.py"]
  interval: 5s
  timeout: 3s
  retries: 3

services:
  aspirational_layer:
    build:
      <<: *default_build
    environment:
      <<:
        - *secrets_environment
        - *rabbitmq_environment
        - *logging_environment
      ACE_RESOURCE_NAME: layer_1
    command: *default_command
    networks: *default_networks
    healthcheck: *healthcheck

  global_strategy_layer:
    build:
      <<: *default_build
    environment:
      <<:
        - *secrets_environment
        - *rabbitmq_environment
        - *logging_environment
      ACE_RESOURCE_NAME: layer_2
    command: *default_command
    depends_on:
      - aspirational_layer
    networks: *default_networks
    healthcheck: *healthcheck

  agent_model_layer:
    build:
      <<: *default_build
    environment:
      <<:
        - *secrets_environment
        - *rabbitmq_environment
        - *logging_environment
      ACE_RESOURCE_NAME: layer_3
    command: *default_command
    depends_on:
      - global_strategy_layer
    networks: *default_networks
    healthcheck: *healthcheck

  executive_function_layer:
    build:
      <<: *default_build
    environment:
      <<:
        - *secrets_environment
        - *rabbitmq_environment
        - *logging_environment
      ACE_RESOURCE_NAME: layer_4
    command: *default_command
    depends_on:
      - agent_model_layer
    networks: *default_networks
    healthcheck: *healthcheck

  cognitive_control_layer:
    build:
      <<: *default_build
    environment:
      <<:
        - *secrets_environment
        - *rabbitmq_environment
        - *logging_environment
      ACE_RESOURCE_NAME: layer_5
    command: *default_command
    depends_on:
      - executive_function_layer
    networks: *default_networks
    healthcheck: *healthcheck

  task_prosecution_layer:
    build:
      <<: *default_build
    environment:
      <<:
        - *secrets_environment
        - *rabbitmq_environment
        - *logging_environment
      ACE_RESOURCE_NAME: layer_6
    command: *default_command
    depends_on:
      - cognitive_control_layer
    networks: *default_networks
    healthcheck: *healthcheck

networks:
  hello-layers_ace-framework-network:
    external: true
